export const weatherCodes: Record<number, string> = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'Partly cloud',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing rime fog',
    51: 'Light drizzle',
    53: 'Moderate drizzle',
    55: 'Intense drizzle',
    56: 'Light freezing drizzle',
    57: 'Intense freezing drizzle',
    61: 'Slight rain',
    63: 'Rain',
    65: 'Heavy rain',
    66: 'Light freezing rain',
    67: 'Heavy freezing rain',
    71: 'Slight snowfall',
    73: 'Snowfall',
    75: 'Heavy snowfall',
    77: 'Snow grains',
    80: 'Slight rain shower',
    81: 'Shower',
    82: 'Violent rain shower',
    85: 'Slight snow shower',
    86: 'Heavy snow shower',
};
